labolatorium 2/Models/Birth.cs
using System;

namespace labolatorium_2.Models
{
    public class Birth
    {
        public string imie { get; set; }
        public DateTime data { get; set; }

        public bool IsValid()
        {
            return !string.IsNullOrEmpty(imie) && data < DateTime.Now;
        }
        public int howold()
        {
            int age = DateTime.Now.Year - data.Year;
            if(DateTime.Now.DayOfYear < data.DayOfYear)
            {
                age--;
            }
            return age;
        }
    }
}

labolatorium 2/Models/Calculator.cs
namespace labolatorium_2.Models
{
    public class Calculator
    {
        public Operators? Operator { get; set; }
        public double? x { get; set; }
        public double? y { get; set; }

        private Dictionary<Operators, String> _opDict = new Dictionary<Operators, string>
        {
            {Operators.add, "+"},
            {Operators.sub, "-"},
            {Operators.mul, "&times;"},
            {Operators.div, "&divide"},
        };

        public string Op
        {
            get
            {
                return _opDict[Operator ?? Operators.add];
            }
        }

        public bool IsValid()
        {
            return Operator != null && x != null && y != null;
        }
        public double Calculate()
        {

            switch (Operator)
            {

                case Operators.add:
                    return (double)(x + y);
                    break;
                case Operators.div:
                    return (double)(x / y);
                    break;
                case Operators.sub:
                    return (double)(x - y);
                    break;
                case Operators.mul:
                    return (double)(x * y);
                    break;
                default: return double.NaN;

            }
        }
    }
}

labolatorium 2/Models/ErrorViewModel.cs
namespace labolatorium_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

labolatorium 2/Models/Operators.cs
namespace labolatorium_2.Models
{
    public enum Operators
    {
        add, sub, mul, div
    }
}

labolatorium 2/Controllers/BirthController.cs
using labolatorium_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace labolatorium_2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Birth()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Result(Birth model)
        {
            if (model.IsValid())
            {
                int wiek = model.howold();
                return View("Result", model);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

labolatorium 2/Controllers/CalculatorController.cs
using labolatorium_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace labolatorium_2.Controllers
{
    public class CalculatorController : Controller
    {
        public enum Operators
        {
            add, sub, mul, div
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Result([FromForm] Calculator model){
            if (!model.IsValid())
            {
                return View("error");
            }
        return View(model);
            
        }
    }
}

labolatorium 2/Controllers/HomeController.cs
using labolatorium_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace labolatorium_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

labolatorium 2/Views/Birth/Birth.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="Result" method="POST">
    Imię: <input type="text" name="imie" />
    <br />
    Data urodzenia:<input type="date" name="data" />
    <br />
    <button type="submit">Wykonaj</button>

</form>

labolatorium 2/Views/Birth/Result.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Masz na imię @Model.imie i masz @Model.howold() lat</p>

labolatorium 2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="Result" method="POST">
    <input type="number" name="x" step="0.0001"/>

    <select name="operator">
        <option value="add">+</option>
        <option value="sub">&minus;</option>
        <option value="mul">&times;</option>
        <option value="div">&divide;</option>
    </select>

    <input type="number" name="y" step="0.0001"/><br />

    <button type="submit">Oblicz</button>
</form>

labolatorium 2/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>@Model.x @Html.Raw(@Model.Op) @Model.y = </p>
<strong>@Model.Calculate()</strong>

labolatorium 2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

labolatorium 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - labolatorium_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/labolatorium_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">labolatorium_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Kalkulator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Birth">BirthController</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - labolatorium_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>